baseURL: 'https://www.peteketcham.com/'
languageCode: en-us
title: Pete's Blog
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-91548413-1

minify:
  disableXML: false
  minifyOutput: true

params:
  env: production
  title: Pete's Blog
  description: >-
    Hobbies, projects, and ideas that I've worked on.  3D printing, home
    improvement projects, code snippets, etc.
  keywords:
    - Blog
    - Portfolio
  author: Pete Ketcham
  images:
    - images/og-cicada.jpg
    - images/tc-cicada.jpg
  DateFormat: 'January 2, 2023'
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

assets:
    favicon: /images/facicon.ico
    favicon16x16: /images/facicon-16x16.ico
    favicon32x32: /images/facicon-32x32.ico
    apple_touch_icon: /images/apple-touch-icon.png

label:
  text: Home
  icon: /images/apple-touch-icon.png
  iconHeight: 35

profileMode:
  enabled: 'true'
  title: Pete's Blog
  subtitle: Thoughts or things
  imageUrl: /images/sq-cicada.jpg
  imageWidth: 240
  imageHeight: 240
  imageTitle: cicada

buttons:
  - name: Posts
    url: posts
  - name: Tags
    url: tags

homeInfoParams:
  Title: "Hi there \U0001F44B"
  Content: Welcome to my blog

socialIcons:
  - name: twitter
    url: 'https://twitter.com/peteketcham'
  - name: github
    url: 'https://github.com/peteketcham'

cover:
  hidden: true
  hiddenInList: true
  hiddenInSingle: true

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys:
    - title
    - permalink
    - summary
    - content

menu: {}

main:
  - identifier: categories
    name: categories
    url: /categories/
    weight: 10
  - identifier: tags
    name: tags
    url: /tags/
    weight: 20
  - identifier: Pete Ketcham
    name: peteketcham.com
    url: 'https://www.peteketcham.com'
    weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON
